name: "Deploy UPT"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  PROJECT_PATH: UPT_UI/UPT_UI.csproj
  
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup .NET
      - uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 3.1.x
      
      - name: Install Dependancies
      - run: dotnet restore ${{ env.PROJECT_PATH }}
        
      - name: Build
      - run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore
        
      - name: Publish
      - run: dotnet publish ${{ env.PROJECT_PATH }} --framework netcoreapp3.1 -c Release --self-contained -r win-x64 -p:PublishSingleFile=true   